before_install:
  - gem update bundler rake
branches:
  only:
    - master
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - "2.0"
  - "2.1"
  - ruby-head
script: bundle exec rspec
